# Generated by Django 3.2.7 on 2021-11-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20211118_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_category',
            name='category_name',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
