# Generated by Django 3.2.7 on 2021-11-17 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Compliance', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('Good_Teaching', models.IntegerField(blank=True, choices=[])),
                ('Nice_Value', models.IntegerField(blank=True, choices=[])),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
