# Generated by Django 3.2.7 on 2021-11-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teachable',
        ),
        migrations.AlterField(
            model_name='detail_category',
            name='detail_name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
