# Generated by Django 3.2.7 on 2021-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211121_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teachable',
            field=models.ManyToManyField(to='mainApp.Detail_Category'),
        ),
    ]
